# Generated by Django 5.2.12 on 2026-03-12 17:30

import catalog_products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_products', '0002_products_description_products_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog_products.models.product_directory_path),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog_products.models.product_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog_products.products')),
            ],
            options={
                'db_table': 'product_images',
                'managed': True,
            },
        ),
    ]
